state_sync_rpc = [
  "http://10.16.57.40:26667",
  "http://10.16.57.40:26667"
]
tendermint_flags = [
    "--p2p.seeds",
    """
      8f956c31e1ca0951e81599b7dd51e3429985a8c0@10.16.57.40:26656
    """,
]

legacy_version = "3.0.1"
upgrade_height = 3050

genesis = """
{
  "genesis_time": "2023-08-08T21:57:43.834611Z",
  "chain_id": "test-chain-3k1M5r",
  "initial_height": "0",
  "consensus_params": {
    "block": {
      "max_bytes": "22020096",
      "max_gas": "-1",
      "time_iota_ms": "1000"
    },
    "evidence": {
      "max_age_num_blocks": "100000",
      "max_age_duration": "172800000000000",
      "max_bytes": "1048576"
    },
    "validator": {
      "pub_key_types": [
        "ed25519"
      ]
    },
    "version": {}
  },
  "validators": [
    {
      "address": "19BD6CB7A1452E54240888311B51DA922E1CD075",
      "pub_key": {
        "type": "tendermint/PubKeyEd25519",
        "value": "3lEU37k5g2v5ayyUbdbCD2VFqi9KTDqzuWSL0zXRhE8="
      },
      "power": "10",
      "name": ""
    }
  ],
  "app_hash": ""
}
"""
