state_sync_rpc = [
  "http://10.16.57.40:26667",
  "http://10.16.57.40:26667"
]
tendermint_flags = [
    "--p2p.seeds",
    """
      8f956c31e1ca0951e81599b7dd51e3429985a8c0@10.16.57.40:26656
    """,
]

legacy_version = "0.0.301"
upgrade_height = 400

genesis = """
{
  "genesis_time": "2023-08-11T20:29:25.043469Z",
  "chain_id": "nomic-internalnet-6",
  "initial_height": "0",
  "consensus_params": {
    "block": {
      "max_bytes": "22020096",
      "max_gas": "-1",
      "time_iota_ms": "1000"
    },
    "evidence": {
      "max_age_num_blocks": "100000",
      "max_age_duration": "172800000000000",
      "max_bytes": "1048576"
    },
    "validator": {
      "pub_key_types": [
        "ed25519"
      ]
    },
    "version": {}
  },
  "validators": [
    {
      "address": "597A4ED9906E1880792942B46FF64BE48EC76D17",
      "pub_key": {
        "type": "tendermint/PubKeyEd25519",
        "value": "5t9I23SLRwWP8ZcfFHIIri2b+c7AA8nx3D7M0Y4cgM0="
      },
      "power": "10",
      "name": ""
    }
  ],
  "app_hash": ""
}
"""
